// Regenerates public/favicon.svg from the same content graph rendered by
// ZeroForcingHero.astro: CONTENT_POINTS as nodes, the Delaunay triangulation
// as edges, the minimum zero forcing set highlighted as seeds. The hero lays
// nodes out by (topic, recency) so the Delaunay triangulation stays planar;
// a favicon has no such constraint and needs legibility at 16-32px instead,
// so nodes are placed evenly around a circle (ordered by angle around the
// data's own centroid, so real neighbors still land near each other and the
// edge count stays true to the actual graph).
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { CONTENT_POINTS } from "../src/data/content-points";
import { relatedIndices, edgesFromNeighbors, MIN_POINTS_FOR_DELAUNAY } from "../src/lib/geometry/related";
import { buildAdjacency, findMinimumZeroForcingSet } from "../src/lib/zeroForcing";

if (CONTENT_POINTS.length < MIN_POINTS_FOR_DELAUNAY) {
  throw new Error(`Need at least ${MIN_POINTS_FOR_DELAUNAY} CONTENT_POINTS to generate a favicon graph.`);
}

const neighborIndices = relatedIndices(CONTENT_POINTS.map((p) => [p.topic, p.recency]));
const indexEdges = edgesFromNeighbors(neighborIndices);
const slugEdges: [string, string][] = indexEdges.map(([a, b]) => [CONTENT_POINTS[a].slug, CONTENT_POINTS[b].slug]);

const graph = buildAdjacency(
  CONTENT_POINTS.map((p) => p.slug),
  slugEdges,
);
const seeds = new Set(findMinimumZeroForcingSet(graph));

const centroidTopic = CONTENT_POINTS.reduce((sum, p) => sum + p.topic, 0) / CONTENT_POINTS.length;
const centroidRecency = CONTENT_POINTS.reduce((sum, p) => sum + p.recency, 0) / CONTENT_POINTS.length;
const angleOrder = CONTENT_POINTS.map((p, i) => ({
  index: i,
  angle: Math.atan2(p.recency - centroidRecency, p.topic - centroidTopic),
})).sort((a, b) => a.angle - b.angle);

const width = 128;
const height = 128;
const radius = 50;
const centerX = width / 2;
const centerY = height / 2;
const nodeRadius = 6;
const seedRadius = 8;
const strokeWidth = 2.2;

const nodes = new Array(CONTENT_POINTS.length);
angleOrder.forEach(({ index }, position) => {
  const theta = (position / CONTENT_POINTS.length) * Math.PI * 2 - Math.PI / 2;
  nodes[index] = {
    slug: CONTENT_POINTS[index].slug,
    x: round(centerX + radius * Math.cos(theta)),
    y: round(centerY + radius * Math.sin(theta)),
  };
});
const nodeBySlug = new Map(nodes.map((n) => [n.slug, n]));

function round(n: number): number {
  return Math.round(n * 100) / 100;
}

const lines = slugEdges
  .map(([a, b]) => {
    const from = nodeBySlug.get(a)!;
    const to = nodeBySlug.get(b)!;
    return `    <line x1="${from.x}" y1="${from.y}" x2="${to.x}" y2="${to.y}" />`;
  })
  .join("\n");

const circles = nodes
  .map((n) => {
    const isSeed = seeds.has(n.slug);
    return `    <circle class="${isSeed ? "seed" : "node"}" cx="${n.x}" cy="${n.y}" r="${isSeed ? seedRadius : nodeRadius}" />`;
  })
  .join("\n");

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">
  <!-- Generated by scripts/generate-favicon.ts from CONTENT_POINTS — do not hand-edit. -->
  <g class="edges">
${lines}
  </g>
  <g class="nodes">
${circles}
  </g>
  <style>
    .edges line { stroke: #9a948a; stroke-width: ${strokeWidth}; stroke-linecap: round; }
    .nodes .node { fill: #171c15; stroke: #ece7d9; stroke-width: ${strokeWidth}; }
    .nodes .seed { fill: #96b481; stroke: #96b481; }
    @media (prefers-color-scheme: light) {
      .nodes .node { fill: #ece7d9; stroke: #171c15; }
    }
  </style>
</svg>
`;

const outPath = fileURLToPath(new URL("../public/favicon.svg", import.meta.url));
writeFileSync(outPath, svg);
console.log(`Wrote ${outPath} (${nodes.length} nodes, ${slugEdges.length} edges, ${seeds.size} seeds)`);
